In [11]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding


'''

Embedding Layer Usage 

'''

# The Embedding has a vocabulary of 50 and an input length of 4
# We will choose a small embedding space of 8 dimensions
# Output from the Embedding layer will be 4 vectors of 4 dimensions each, one for each word. 
# We flatten this to a one 32-element vector to pass on to the Dense output layer.

# define documents
docs = ['Well done!','Good work','Great effort','nice work','Excellent!',
'Weak','Poor effort!','not good','poor work','Could have done better.']

# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])

# integer encode the documents
print('One-Hot-Encoded:\n')
vocab_size = 20
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, 
                            maxlen=max_length, 
                            padding='post')
print('\nPadded Documents\n')
print(padded_docs)

# define the model
print('\nBinary Classification Model\n')
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', 
              loss='binary_crossentropy', 
              metrics=['accuracy'])
print(model.summary())

# # fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)

print('\nEvaluation\n')
print('Accuracy: %f' % (accuracy*100))

One-Hot-Encoded:

[[18, 18], [11, 10], [1, 10], [17, 10], [4], [4], [11, 10], [2, 11], [11, 10], [18, 10, 18, 10]]

Padded Documents

[[18 18  0  0]
 [11 10  0  0]
 [ 1 10  0  0]
 [17 10  0  0]
 [ 4  0  0  0]
 [ 4  0  0  0]
 [11 10  0  0]
 [ 2 11  0  0]
 [11 10  0  0]
 [18 10 18 10]]

Binary Classification Model

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_10 (Embedding)     (None, 4, 8)              160       
_________________________________________________________________
flatten_10 (Flatten)         (None, 32)                0         
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None

Evaluation

Accuracy: 69.999999
